### ISSUE TITLE
Add an option to ignore logs about heartbeat message running examples

### ISSUE THREAD

**Issue by broccolism** [lablup/raftify#110]
### Why needed
- Since heartbeat occurs every few microseconds, logs about it might make other important logs to be missed or difficult to catch.
- It is quite obvious that heartbeat messages are being exchanged when everything works normally.
### Suggestion
- It would be great if I could pass an option on command line parameter when running examples.
- 🧐 There's two ways to implement this:
  1. Add an option to turn off the logs about heartbeat messages.
  2. Or an option to select log level.
- The second one looks better since it is more general way. If we do so, I think it is also needed to change some code where it's set to the debug level but actually should be another level. (For example, `logger.debug(format!("Connection error: {:?}", e).as_str());` ?)

**Comment by broccolism** [comment]
@jopemachine Which one would be better? Or if you have any other idea, please let me know :D

**Comment by rapsealk** [comment]
I'd suggest adding an option to select the log level (as option ii), specifically setting the `verbose` or [`trace`](https://docs.rs/log/latest/log/enum.Level.html#variant.Trace) level for the heartbeat logs.

**Comment by jopemachine** [comment]
The log level is already implemented through `slog`.
You can change the log level using slog's `LevelFilter`.
For example, the log level for heartbeat messages is `DEBUG`.
Therefore, if you set the slog `LevelFilter` to `INFO`, the logs indicating that the heartbeat has been sent and received will not be displayed.

```
...
    let decorator = slog_term::TermDecorator::new().build();
    let drain = slog_term::FullFormat::new(decorator).build().fuse();
    let drain = slog_async::Async::new(drain).build().fuse();
    let drain = slog::LevelFilter::new(drain, slog::Level::Info).fuse(); // Set log level here

    let mut builder = LogBuilder::new(drain);
    builder = builder.filter(None, slog::FilterLevel::Debug);

    if let Ok(s) = std::env::var("RUST_LOG") {
        builder = builder.parse(&s);
    }
    let drain = builder.build().fuse();

    let logger = Arc::new(Slogger {
        slog: slog::Logger::root(drain, o!()),
    });
...
```

Additionally, in the development environment example code, the `heartbeat_tick` is set to a very short value, which tends to spam the terminal with the heartbeat messages, but you can change this value to a larger one.

Nevertheless, in the development environment, I think there could be cases where you want to keep the log level at DEBUG without wishing to see heartbeat messages.

So I think it would be good to define an option in the `Config` to omit only the output of heartbeat messages.

**Comment by jopemachine** [comment]
For your information, this option will require changes to the raft-rs source code.
For raftify, we are currently using the following `raft-rs` source code, which includes some patches.

https://github.com/jopemachine/raft-rs

**Comment by broccolism** [comment]
@rapsealk @jopemachine Thank you for your comments!
I'm gonna leave the heartbeat message's log level.

I was considering `setting the verbose or trace level for the heartbeat logs` as @rapsealk told at first,
but I agree with `there could be cases where you want to keep the log level at DEBUG without wishing to see heartbeat messages`. 
If we adjust heartbeat message's log level as verbose, we will still need to see the log even using debug level...


---
And I have a question about where to change.


#### Where to modify
> For your information, this option will require changes to the raft-rs source code.

I was thinking about just adding a new field `log_level` on `Options` struct of [example codes here](https://github.com/lablup/raftify/blob/main/examples/memstore/static-members/src/main.rs#L29-L48) like this, so that we can pass `log_level` parameter
```rust
async fn main() -> std::result::Result<(), Box<dyn std::error::Error>> {
    color_backtrace::install();

    let decorator = slog_term::TermDecorator::new().build();
    let drain = slog_term::FullFormat::new(decorator).build().fuse();
    let drain = slog_async::Async::new(drain).build().fuse();
    /* =============== from here ============================ */
    let options = Options::from_args();
    let filter_level = match options.log_level.to_lowercase().as_str() {
        "trace" => slog::FilterLevel::Trace,
         // .....
        _ => slog::FilterLevel::Debug,
    };
    let mut builder = LogBuilder::new(drain);
    builder = builder.filter(None, filter_level);
    /* =============== to here ============================ */
```

<img width="850" alt="image" src="https://github.com/user-attachments/assets/4fb932d3-1a43-4ed6-a3f5-63b67e906c89">

...
this worked for some logs but not for the logs left by RaftCore as above.
I think this is why you told me to modify the raft-rs code, but I couldn't figure out where to change.
I've found [`default_logger`](https://github.com/tikv/raft-rs/blob/2aefbf627f243dd261b7585ef1250d32efd9dfe7/src/lib.rs#L574) function, but is it used for creating raft node...?

**Comment by rapsealk** [comment]
The log must be coming from here:
https://github.com/tikv/raft-rs/blob/2aefbf627f243dd261b7585ef1250d32efd9dfe7/src/raft.rs#L1262-L1266

According to the [`slog_envlogger`](https://docs.rs/slog-envlogger/latest/slog_envlogger/#enabling-logging), which `default_logger()` relies on, the `RUST_LOG` environment variable controls the log level. I set the environment variable as follows:

```sh
$ RUST_LOG=DEBUG ./target/debug/memstore-static-members --raft-addr=127.0.0.1:60061 --web-server=127.0.0.1:8001
```

However, the issue is that setting `RUST_LOG` to `DEBUG` does not suppress `INFO` level logs, as `INFO` is a higher priority than `DEBUG`. To filter out `INFO` logs, you might try setting `RUST_LOG` to `ERROR`, while it may not be a comprehensive solution for all cases. Maybe we need to fork [tikv/raft-rs](https://github.com/tikv/raft-rs) to handle this. How do you think about this @jopemachine?

By the way, which branch or HEAD commit are you working with? I am getting similar logs but with different levels: `ERROR` -> `DEBUG`
![image](https://github.com/user-attachments/assets/52568f9b-0d6e-4da9-90d1-8b1b4a52ef34)

**Comment by rapsealk** [comment]
> For your information, this option will require changes to the raft-rs source code. For raftify, we are currently using the following `raft-rs` source code, which includes some patches.
> 
> https://github.com/jopemachine/raft-rs

Ah, raftify is already using a forked one. Sounds good.

**Comment by jopemachine** [comment]
The log that a message, including a heartbeat, was sent is output through the line below in the patched `raft-rs` source code.

https://github.com/jopemachine/raft-rs/blob/master/src/raft.rs#L610-L617

Therefore, to omit only the output of the heartbeat message *regardless of the log level*, the following line should be patched.

Additionally, for reference, the log that a "RaftMessage was received" is output at the following line in raftify. 

https://github.com/lablup/raftify/blob/7611093a2113b87edfd6e6283f63a7497100b34e/raftify/src/raft_node/mod.rs#L1248-L1256

**Comment by broccolism** [comment]
@rapsealk 

> By the way, which branch or HEAD commit are you working with? I am getting similar logs but with different levels: ERROR -> DEBUG

Oh my branch has been outdated. I pulled main branch and the log level is now DEBUG. Thanks!

<img width="793" alt="image" src="https://github.com/user-attachments/assets/16a65c8e-3060-4976-95c5-b028256dc435">

---

@jopemachine Ahh so the logs are left by:
- `raft-rs(forked)/src/raft`: outgoing messages
- `raftify/raftify/src/raft_node`: incoming messages;
It's a little bit confusing 😂 I'm gonna work with them. Thank you!
