### ISSUE TITLE
How does raftify forward requests to specific nodes?

### ISSUE THREAD

**Issue by zzl221000** [lablup/raftify#123]
I need to implement a stateful request, and the current examples only read from the store of the current node.
For example: I have three raft nodes, 0, 1, 2. Now I want to implement a function to traverse the hashstore, generate a cursor ID bound to a fixed node, and return the data in batches.

**Comment by jopemachine** [comment]
In the current implementation of the Raftify code, read and write requests are all handled by the leader to maintain strong consistency, so requests cannot be forwarded to specific nodes.

**Comment by zzl221000** [comment]
Thank you
