### ISSUE TITLE
Compare the `first_index` when appending the entries to compacted log storage

### ISSUE THREAD

**Issue by inchori** [lablup/raftify#127]
When running a `test_storage_append` in `heed_storage.rs`, it should return an error because the compacted log entries and the log entries that will be appended to be first indexes are different.

So, it should add the logic for comparing `first_index` in `HeedStorageCore`'s `append` function.

**Comment by jopemachine** [comment]
Yes, that's correct. 
You can refer to the append implementation of the in-memory storage to implement simple exception handling. 
But be careful to ensure that the added exception handling does not break other use cases.

**Comment by inchori** [comment]
Ok, after implementing, I'll also write integration test based on the snapshot scenario.
