### ISSUE TITLE
Implement `Rocksdb` storage

### ISSUE THREAD

**Issue by jopemachine** [lablup/raftify#93]
It would be helpful to implement various log storage types and benchmark their performance.

**Comment by TaskerJang** [comment]
### Goal
The goal is to implement RocksDB storage in the project, enabling the use of the RocksDB engine to store logs. 

### Tasks

1. **Implement RocksDB Storage:**
   - Define a new storage module or structure that manages and stores log data using RocksDB.
   - This structure should implement the `StableStorage` trait to integrate seamlessly with the existing codebase.

2. **Utilize RocksDB Methods:**
   - Implement log storage, retrieval, and deletion functions using RocksDB's core methods (`put`, `get`, `delete`, etc.).
   - Ensure the implementation efficiently handles large data volumes while maintaining performance and reliability.

3. **Integrate with Existing Codebase:**
   - Ensure the new RocksDB storage implementation is compatible with the existing storage interface and can be easily swapped with other storage types.
   - Modify relevant parts of the codebase to allow the selection of different storage backends during configuration or runtime.

4. **Performance Benchmarking:**
   - After implementation, benchmark the performance of RocksDB storage against other storage types to evaluate its efficiency and suitability.
   - Compare relevant metrics such as read/write speed and memory usage to provide insights into the optimal storage options for various scenarios.

### Things to Learn

1. **RocksDB Basics:**
   - Study [RocksDB's official documentation](https://github.com/facebook/rocksdb/wiki) to understand its internal structure and operation.
   - Focus on key concepts such as `Column Families`, `Write-Ahead Logging (WAL)`, `Compaction`, and `Snapshots`.

2. **Integrating RocksDB with Rust:**
   - Learn how to use the [Rust RocksDB library](https://crates.io/crates/rocksdb) to interact with RocksDB in Rust.
   - Master the API for creating, reading, writing, and deleting databases in Rust using RocksDB.

3. **Rust Traits and Interfaces:**
   - Study Rust’s trait system, particularly how to implement traits like `StableStorage`.
   - Deepen your understanding of Rust's structs, generics, and lifetimes to write safe and efficient code.

4. **Performance Optimization and Benchmarking:**
   - Learn optimization techniques in Rust (e.g., memory management, asynchronous processing, I/O optimization).
   - Use benchmarking tools like [criterion.rs](https://crates.io/crates/criterion) to measure and improve performance in Rust.

5. **Understanding the Raft Consensus Algorithm:**
   - Study the [Raft consensus algorithm paper](https://raft.github.io/raft.pdf) to understand its operation.
   - Learn how the Raft algorithm handles log replication and how it can integrate with storage engines like RocksDB.


### For example

![image](https://github.com/user-attachments/assets/6d4a1393-4bb2-4e5c-a982-e46aa91966b4)

**Comment by TaskerJang** [comment]
https://github.com/lablup/raftify/pull/124
